### ISSUE TITLE
pcb antenna design

### ISSUE THREAD

**Issue by maxholgasson** [cernohorsky/LoRa-Node#3]
Hi,

which inductor L1 is used in the circuit? Also which values or specific caps for C3 and C4?
Thanks

**Comment by miqmago** [comment]
@maxholgasson on BOM I've seen that L1 is 0R and C3 and C4 are not placed. From the TI design referenced on readme, it seems to me that they are not needed if the ground plane is 31x45mm.

I'm not sure about L1, as you closed the issue as resolved, could you confirm if it can be skipped and wired it directly to RFM95W ANT pin?
